GET http://localhost:3001/eventos


###
# @name criarEvento
POST http://localhost:3001/eventos
Content-Type: application/json

{
  "nome": "event 1",
  "descricao": "event 1 description",
  "data": "2024-06-02T10:23:14",
  "preco": 100.10
}

###

@eventoId = {{ criarEvento.response.body.id }}

###
GET http://localhost:3001/eventos/{{eventoId}}/lugares

###
# @name criarLugar
POST http://localhost:3001/eventos/{{eventoId}}/lugares
Content-Type: application/json

{
  "nome": "spot 2"
}

###

@lugarNome = {{ criarLugar.response.body.name }}

### Reserve spots

POST http://localhost:3001/eventos/{{eventoId}}/reservar
Content-Type: application/json
X-Api-Token: 000

{
  "lugares": ["{{lugarNome}}"],
  "tipo_ingresso": "inteira",
  "email": "user1@test.com"
}