GET http://localhost:8080/events

###

GET http://localhost:8080/events/bd5eac7f-f2c7-49d5-8789-e59c0a107b12

###

POST http://localhost:8080/events HTTP/1.1
Content-Type: application/json

{
    "name": "Tech Conference 2025",
    "location": "Convention Center",
    "organization": "Tech Innovators Inc.",
    "rating": "L14",
    "date": "2024-09-15T09:00:00Z",
    "capacity": 500,
    "price": 150.0,
    "partner_id": 2,
    "image_url": "http://example.com/image.jpg",
    "spots": ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10"]
}

###

POST http://localhost:8080/checkout HTTP/1.1
Content-Type: application/json

{
    "event_id": "2f8c9dcb-56ea-4e9b-a1c6-5fe711c47416",
    "spots": ["A1"],
    "ticket_kind": "full",
    "card_hash": "example_card_hash",
    "email": "user@example.com"
}

