module.exports = {
    events: [
      {
        id: 1,
        name: "cerulean",
        organization: "organization 1",
        date: "2023-09-09T00:00:00",
        price: 100,
        rating: "10",
        image_url: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
        created_at: "2023-09-09T00:10:10",
        location: "location 1",
      },
      {
        id: 2,
        name: "fuchsia rose",
        organization: "organization 2",
        date: "2023-09-10T00:00:00",
        price: 200,
        rating: "12",
        image_url: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14",
        created_at: "2023-09-09T00:10:10",
        location: "location 2",
      },
      {
        id: 3,
        name: "true red",
        organization: "organization 3",
        date: "2023-09-11T00:00:00",
        price: 300,
        rating: "14",
        image_url: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec",
        created_at: "2023-09-09T00:10:10",
        location: "location 3",
      },
    ],
    spots: [
        {id: 1, name: "A1", status: 'available', event_id: 1},
        {id: 2, name: "A2", status: 'available', event_id: 1},
        {id: 3, name: "A3", status: 'available', event_id: 1},
        {id: 4, name: "A4", status: 'available', event_id: 1},
        {id: 5, name: "A5", status: 'available', event_id: 1},
        {id: 6, name: "B1", status: 'available', event_id: 1},
        {id: 7, name: "B2", status: 'available', event_id: 1},
        {id: 8, name: "B3", status: 'available', event_id: 1},
        {id: 9, name: "B4", status: 'available', event_id: 1},
        {id: 10, name: "B5", status: 'available', event_id: 1},

        {id: 1, name: "A1", status: 'available', event_id: 2},
        {id: 2, name: "A2", status: 'available', event_id: 2},
        {id: 3, name: "A3", status: 'available', event_id: 2},
        {id: 4, name: "A4", status: 'available', event_id: 2},
        {id: 5, name: "A5", status: 'available', event_id: 2},
        {id: 6, name: "A6", status: 'available', event_id: 2},
        {id: 7, name: "A7", status: 'available', event_id: 2},
        {id: 8, name: "A8", status: 'available', event_id: 2},
        {id: 9, name: "A9", status: 'available', event_id: 2},
        {id: 10, name: "A10", status: 'available', event_id: 2},
        {id: 11, name: "B1", status: 'available', event_id: 2},
        {id: 12, name: "B2", status: 'available', event_id: 2},
        {id: 13, name: "B3", status: 'available', event_id: 2},
        {id: 14, name: "B4", status: 'available', event_id: 2},
        {id: 15, name: "B5", status: 'available', event_id: 2},
        {id: 16, name: "B6", status: 'available', event_id: 2},
        {id: 17, name: "B7", status: 'available', event_id: 2},
        {id: 18, name: "B8", status: 'available', event_id: 2},
        {id: 19, name: "B9", status: 'available', event_id: 2},
        {id: 20, name: "B10", status: 'available', event_id: 2},

        {id: 1, name: "A1", status: 'available', event_id: 3},
        {id: 2, name: "A2", status: 'available', event_id: 3},
        {id: 3, name: "A3", status: 'available', event_id: 3},
        {id: 4, name: "A4", status: 'available', event_id: 3},
        {id: 5, name: "A5", status: 'available', event_id: 3},
        {id: 6, name: "A6", status: 'available', event_id: 3},
        {id: 7, name: "A7", status: 'available', event_id: 3},
        {id: 8, name: "A8", status: 'available', event_id: 3},
        {id: 9, name: "A9", status: 'available', event_id: 3},
        {id: 10, name: "A10", status: 'available', event_id: 3},
        {id: 11, name: "A11", status: 'available', event_id: 3},
        {id: 12, name: "A12", status: 'available', event_id: 3},
        {id: 13, name: "A13", status: 'available', event_id: 3},
        {id: 14, name: "A14", status: 'available', event_id: 3},
        {id: 15, name: "A15", status: 'available', event_id: 3},
        {id: 16, name: "B1", status: 'available', event_id: 3},
        {id: 17, name: "B2", status: 'available', event_id: 3},
        {id: 18, name: "B3", status: 'available', event_id: 3},
        {id: 19, name: "B4", status: 'available', event_id: 3},
        {id: 20, name: "B5", status: 'available', event_id: 3},
        {id: 21, name: "B6", status: 'available', event_id: 3},
        {id: 22, name: "B7", status: 'available', event_id: 3},
        {id: 23, name: "B8", status: 'available', event_id: 3},
        {id: 24, name: "B9", status: 'available', event_id: 3},
        {id: 25, name: "B10", status: 'available', event_id: 3},
        {id: 26, name: "B11", status: 'available', event_id: 3},
        {id: 27, name: "B12", status: 'available', event_id: 3},
        {id: 28, name: "B13", status: 'available', event_id: 3},
        {id: 29, name: "B14", status: 'available', event_id: 3},
        {id: 30, name: "B15", status: 'available', event_id: 3},
    ]
  };
  